config/routes.rb
Rails.application.routes.draw do
  root 'recommendations#show', as: :recommendations_show

  patch 'recommendations/update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recommendation.rb
require "open-uri"
require "json"

class Recommendation
  MAX_ARTICLE_QUERIES = 10
  CANDIDATE_CHANCE = 2 # multiplied by the ratio (candidate_score / top user
  # category score), to get a probability that a candidate will be selected
  # early, before max_article_queries is reached.

  attr_reader :title, :description, :extract, :url, :thumbnail_source,
              :categories, :article_type, :related_articles

  def initialize(user_category_scores,
                  article_type: :any,
                  max_article_queries: MAX_ARTICLE_QUERIES,
                  candidate_chance: CANDIDATE_CHANCE)
    @article_type = article_type.to_sym
    @max_article_queries = max_article_queries
    @candidate_chance = candidate_chance
    summary, @categories, _candidate_score =
      recommended_summary_and_categories(user_category_scores)
    @title = summary["title"]
    @description = summary["description"]
    @extract = summary["extract"]
    @url = summary.dig("content_urls", "desktop", "page")
    @thumbnail_source = summary.dig("thumbnail", "source")
    # @related_articles = related_articles(summary)
  end

  def simple_categories
    from_categories_response(categories, "prediction")
  end

  def to_h
    {
      title: title,
      description: description,
      url: url,
      extract: extract,
      thumbnail_source: thumbnail_source
    }
  end

  private

  def recommended_summary_and_categories(user_category_scores)
    candidates = []
    (1..@max_article_queries).each do |query_n|
      article = random_article(type: @article_type)
      revision_id = article["revision"]
      article_categories = categories_for_id(revision_id)
      score = candidate_score(article_categories, user_category_scores)
      candidates << [article, article_categories, score]
      if good_enough_candidate?(score, user_category_scores)
        Rails.logger.info "GOOD ENOUGH CANDIDATE after #{query_n} queries, score #{score}"
        return candidates.last
      end
    end
    candidates.max_by(&:last)
  end

  def candidate_score(categories_response, category_scores)
    top_categories = categories_prediction(categories_response)
    probabilities = categories_probability(categories_response)
    top_categories.map do |category|
      probabilities[category] * (category_scores[category] || 0)
    end.sum
  end

  def good_enough_candidate?(score, user_category_scores)
    return false if score < 0
    return true if user_category_scores.empty?
    top_category_score = user_category_scores.max_by { |_category, score| score }.last
    probability = @candidate_chance * (score / top_category_score)
    probability > 1 || rand < probability
  end

  def categories_prediction(categories_response)
    from_categories_response(categories_response, "prediction")
  end

  def categories_probability(categories_response)
    from_categories_response(categories_response, "probability")
  end

  def from_categories_response(categories_response, key)
    categories_response.dig("enwiki", "scores")
                        .values.first.dig("articletopic", "score", key)
  end

  def categories_for_id(revision_id)
    # from https://stackoverflow.com/a/65801715/4158773
    # list of topics: https://www.mediawiki.org/wiki/ORES/Articletopic
    categories_url =
      "https://ores.wikimedia.org/v3/scores/enwiki/?models=articletopic&revids=#{revision_id}"
    JSON.parse(URI.open(categories_url).read)
  end

  # Wikipedia REST API documentation: https://en.wikipedia.org/api/rest_v1/#/Page%20content
  def random_article(type: :any)
    case type
    when :good
      random_x_article("Good_articles")
    when :featured
      random_x_article("Featured_articles")
    else
      summary_url = "https://en.wikipedia.org/api/rest_v1/page/random/summary"
      JSON.parse(URI.open(summary_url).read)
    end
  end

  def random_x_article(query_string)
    redirect_url = URI("https://randomincategory.toolforge.org/#{query_string}")
    redirect = Net::HTTP.get_response(redirect_url)
    article_url = redirect["location"]
    title = article_url.split("/").last
    summary_url = "https://en.wikipedia.org/api/rest_v1/page/summary/#{escape(title)}"
    JSON.parse(URI.open(summary_url).read)
  end

  def related_articles(summary)
    JSON.parse(URI.open("https://en.wikipedia.org/api/rest_v1/page/related/#{escape(@title)}").read)
  rescue OpenURI::HTTPError
    Rails.logger.error "Unable to get related articles for \"#{@title}\" #{@url}"
    nil
  end

  def escape(title)
    URI::DEFAULT_PARSER.escape(title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  STARTER_CATEGORY_SCORE = 10
  MAX_SESSION_BYTESIZE = 1850

  def show
    @user_category_scores = category_scores.sort_by { |_category, score| -score }
                                             .to_h
    @starter_categories = session[:starter_categories_string] ||
                                  Ores::Categories::DEFAULT_STRING
    @article_type = session[:article_type]&.to_sym || :any
    @recommendation = session[:recommendation]
  end

  def update
    store_starter_categories
    store_article_type
    add_like_or_dislike_into_category_scores
    get_and_store_recommendation
    if session_cookie_full?
      session[:recommendation] = nil
      session[:starter_categories] = nil
      redirect_to recommendations_show_path, status: "303",
        alert: "You've reached the storage size limit! Soon you'll be able to " \
               "sign up and use more data. For now, try specifying fewer or " \
               "more specific categories."
    else
      redirect_to recommendations_show_path, status: "303"
    end
  end

  private

  def session_cookie_full?
    session_data = session[:starter_categories_string].to_s +
                   session[:starter_categories].to_s +
                   session[:article_type].to_s +
                   session[:recommendation].to_s +
                   session[:recommendation_categories].to_s +
                   session[:category_scores].to_s
    Rails.logger.info "SESSION SIZE: #{session_data.bytesize}"
    session_data.bytesize > MAX_SESSION_BYTESIZE
  end

  def preferences_submitted?
    session.has_key?(:starter_categories)
  end

  def category_scores
    session[:category_scores] ||= {}
    starter_scores = (session[:starter_categories] || {})
      .map { |category| [category, STARTER_CATEGORY_SCORE] }.to_h
    session[:category_scores]
      .merge(starter_scores) do |_category, liked_score, starter_score|
      liked_score + starter_score
    end
  end

  def store_article_type
    session[:article_type] = params[:article_type]
  end

  def store_starter_categories
    session[:starter_categories_string] = params[:starter_categories]
    session[:starter_categories] = Ores::Categories.from_string(params[:starter_categories])
  end

  def add_like_or_dislike_into_category_scores
    liked_increment = Integer(params[:liked], exception: false) || (return false)
    session[:category_scores] ||= {}
    (session[:recommendation_categories] || []).each do |category|
      session[:category_scores][category] =
      session[:category_scores].fetch(category, 0) + liked_increment
    end
  end

  def get_and_store_recommendation
    recommendation = Recommendation.new(category_scores,
                                        article_type: session[:article_type])
    store_recommendation_categories(recommendation)
    session[:recommendation] = recommendation.to_h
  end

  def store_recommendation_categories(recommendation)
    session[:recommendation_categories] = recommendation.simple_categories
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <%= render 'shared/meta' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://unpkg.com/papercss@1.8.2/dist/paper.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="paper container margin-top-large margin-bottom-large">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/recommendations/_article_type.html.erb
<fieldset class="form-group margin-top margin-bottom-none">
  <legend>Article type:</legend>
  <%= form.label :article_type_any, class: "paper-radio margin-right", style: "display:inline-block" do %>
    <%= form.radio_button :article_type, "any", checked: (article_type == :any) %>
    <span>Any (fast)</span>
  <% end %>
  <%= form.label :article_type_good, class: "paper-radio margin-right", style: "display:inline-block" do %>
    <%= form.radio_button :article_type, "good", checked: (article_type == :good) %>
    <span>Good</span>
  <% end %>
  <%= form.label :article_type_featured, class: "paper-radio", style: "display:inline-block" do %>
    <%= form.radio_button :article_type, "featured", checked: (article_type == :featured) %>
    <span>Featured</span>
  <% end %>
</fieldset>

app/views/recommendations/_category_scores.html.erb
<h4>Your category scores:</h4>

<% if category_scores.empty? %>
  <p>None yet. Give a thumbs up/down to an article, or specify categories that you're interested in.</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Category</th>
        <th>Score</th>
      </tr>
    </thead>
    <tbody>
    <% category_scores.each do |category, score| %>
        <tr>
          <td><%= category %></td>
          <td><%= score %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/recommendations/_like_dislike.html.erb
<fieldset class="form-group margin-top-large">
  <legend>Did you like this article?</legend>
  <%= form.label :liked_1, class: "paper-radio margin-right-large", style: "display:inline-block" do %>
    <%= form.radio_button :liked, 1 %>
    <span>👍</span>
  <% end %>
  <%= form.label :"liked_-1", class: "paper-radio", style: "display:inline-block" do %>
    <%= form.radio_button :liked, -1 %>
    <span>👎</span>
  <% end %>
</fieldset>

app/views/recommendations/_recommendation.html.erb
<div id="recommendation" class="paper container">
  <h2 style="margin:0 0 1rem 0"><%= recommendation["title"] %></h2>
  <p><em><%= recommendation["description"] %></em></p>
  <p><%= link_to recommendation["url"], recommendation["url"], target: "_blank" %></p>
  <p><%= recommendation["extract"] %></p>
  <% unless recommendation["thumbnail_source"].nil? %>
    <p><%= image_tag recommendation["thumbnail_source"] %></p>
  <% end %>
</div>

app/views/recommendations/_starter_categories.html.erb
<%= form.label :starter_categories, "What categories are you interested in? From #{link_to "this list.", "https://www.mediawiki.org/wiki/ORES/Articletopic", target: "_blank"}".html_safe %>
<%= form.text_field :starter_categories,
                  value: starter_categories,
                  class: "margin-top-small",
                  style: "width:100%" %>

app/views/recommendations/show.html.erb
<h1 style="margin:0 0 1rem 0">Wiki Stumble</h1>

<%= form_with url: recommendations_update_path, method: :patch do |f| %>
  <%= render 'recommendations/starter_categories', form: f, starter_categories: @starter_categories %>
  <%= render 'recommendations/article_type', form: f, article_type: @article_type %>

  <%= f.submit "Next article", class: "paper-btn margin-top" %>

  <% unless @recommendation.nil? %>
    <%= render 'recommendations/like_dislike', form: f %>
  <% end %>
<% end %>

<% unless @recommendation.nil? %>
  <%= render 'recommendations/recommendation', recommendation: @recommendation %>
  <%= render 'recommendations/category_scores', category_scores: @user_category_scores %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-primary margin-top-small">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer" class="paper container-lg margin-bottom-none">
  <small>
    <a href="https://github.com/fpsvogel/wikistumble-rails">GitHub repo</a>. - Made by <a href="https://fpsvogel.com/">Felipe Vogel</a>. -
    Powered by <a href="https://rubyonrails.org/">Ruby on Rails</a>, <a href="https://www.getpapercss.com/">PaperCSS</a>, and Wikimedia <a href="https://en.wikipedia.org/api/rest_v1/">REST</a> and <a href="https://ores.wikimedia.org/">ORES</a> APIs.
  </small>
</div>

app/views/shared/_meta.html.erb
<title>Wiki Stumble</title>
<meta name="description" content="Discover interesting Wikipedia articles through personalized recommendations." />
<link rel="canonical" href="https://wikistumble.herokuapp.com/" />

<meta property="og:title" content="Wiki Stumble: Explore Wikipedia" />
<meta property="og:description" content="Discover interesting Wikipedia articles through personalized recommendations." />
<meta property="og:url" content="https://wikistumble.herokuapp.com/" />
<meta property="og:image" content="https://wikistumble.herokuapp.com/android-chrome-512x512.png" />
<meta property="og:type" content="website" />

<meta name="twitter:card" content="summary" />
<meta property="twitter:image" content="https://wikistumble.herokuapp.com/android-chrome-512x512.png" />
<meta property="twitter:title" content="Wiki Stumble: Explore Wikipedia" />
<meta property="twitter:description" content="Discover interesting Wikipedia articles through personalized recommendations." />
<meta name="twitter:creator" content="@fpsvogel" />